# Généré par crandore_init() le 2026-03-09
# Modifiez ce fichier selon vos besoins et lancez :
#   docker compose run --rm crandore-stack

settings:
  local_root: /minicran
  packages:
    # ignoré (full_snapshot: true dans les profils)

profiles:
  linux_44:
    os: linux
    r_version: "4.4"
    arch: x86_64
    distros: [noble]
    full_snapshot: true

snapshots:
  2026-03-09:
    profiles:
      - linux_44
